/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkshopRouteImport } from './routes/app.workshop'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppCustomersRouteImport } from './routes/app.customers'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopRoute = AppWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/services': typeof AppServicesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/services': typeof AppServicesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/services': typeof AppServicesRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/customers'
    | '/app/finance'
    | '/app/inventory'
    | '/app/services'
    | '/app/staff'
    | '/app/tickets'
    | '/app/workshop'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/customers'
    | '/app/finance'
    | '/app/inventory'
    | '/app/services'
    | '/app/staff'
    | '/app/tickets'
    | '/app/workshop'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/customers'
    | '/app/finance'
    | '/app/inventory'
    | '/app/services'
    | '/app/staff'
    | '/app/tickets'
    | '/app/workshop'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workshop': {
      id: '/app/workshop'
      path: '/workshop'
      fullPath: '/app/workshop'
      preLoaderRoute: typeof AppWorkshopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppServicesRoute: typeof AppServicesRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppWorkshopRoute: typeof AppWorkshopRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppServicesRoute: AppServicesRoute,
  AppStaffRoute: AppStaffRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppWorkshopRoute: AppWorkshopRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
